2017-04-03 18:11:47,256 [9] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:16:36,347 [15] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:18:37,287 [13] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:19:07,698 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:20:19,038 [24] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:21:13,500 [30] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:21:30,208 [21] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:22:27,074 [23] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:23:01,127 [20] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:24:03,731 [11] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:41:03,782 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:42:13,621 [30] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:43:13,968 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:45:17,444 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:50:31,935 [5] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,130 [5] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,209 [12] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,241 [17] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,303 [12] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,303 [19] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,316 [17] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:50:32,316 [12] ERROR AnJie.ERP.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2017-04-03 18:51:03,297 [10] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:52:13,847 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:56:19,656 [21] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:57:04,127 [8] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:57:26,217 [22] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:57:49,810 [22] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:58:15,482 [25] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 18:58:41,539 [25] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:21:19,210 [40] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:21:50,709 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:23:55,346 [8] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:24:08,088 [8] ERROR AnJie.ERP.DataAccess.DbHelper - 变量名 '@ZoneId' 已声明。变量名在查询批次或存储过程内部必须唯一。
必须声明标量变量 "@LocationId"。
2017-04-03 19:24:12,457 [6] ERROR AnJie.ERP.DataAccess.DbHelper - 变量名 '@ZoneId' 已声明。变量名在查询批次或存储过程内部必须唯一。
必须声明标量变量 "@LocationId"。
2017-04-03 19:24:13,174 [8] ERROR AnJie.ERP.DataAccess.DbHelper - 变量名 '@ZoneId' 已声明。变量名在查询批次或存储过程内部必须唯一。
必须声明标量变量 "@LocationId"。
2017-04-03 19:24:13,675 [10] ERROR AnJie.ERP.DataAccess.DbHelper - 变量名 '@ZoneId' 已声明。变量名在查询批次或存储过程内部必须唯一。
必须声明标量变量 "@LocationId"。
2017-04-03 19:26:25,881 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:27:13,003 [8] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:27:20,819 [15] ERROR AnJie.ERP.DataAccess.DbHelper - 变量名 '@ZoneId' 已声明。变量名在查询批次或存储过程内部必须唯一。
必须声明标量变量 "@LocationId"。
2017-04-03 19:28:05,672 [15] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:41:18,053 [39] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:42:06,070 [39] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:44:52,070 [27] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:58:22,676 [43] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 19:59:13,860 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:00:26,903 [7] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:07:01,252 [19] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:08:58,849 [20] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:28:46,965 [66] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:32:05,564 [77] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:32:56,627 [66] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:33:34,657 [66] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:34:39,440 [77] ERROR AnJie.ERP.DataAccess.DbHelper - 参数化查询 '(@ProductId nvarchar(4000))Select Count(1) From (
             ' 需要参数 '@ProductId'，但未提供该参数。
2017-04-03 20:44:18,723 [10] ERROR AnJie.ERP.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-04-03 20:45:08,828 [5] ERROR AnJie.ERP.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
